spring:
  application:
    name: ml-payment-recovery-dashboard
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:mlpayments;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

mercadopago:
  base-url: ${MP_BASE_URL:https://api.mercadopago.com}
  token: ${MP_TOKEN:APP_USR-7176507038713643-050417-3b741e2758df4536e3c6185ce6155bf7-3379089790}
  public-key: ${MP_PUBLIC_KEY:APP_USR-944360ae-5621-4465-824d-991a4e9061d3}
  mock-enabled: ${MP_MOCK_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  flyway:
    enabled: true
